baseURL = "https://gestrada.dev/"
title = "gestrada.dev"
theme = "hugo-coder"
languagecode = "en-us"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[markup.goldmark.renderer]
    unsafe = true

# Coder Theme Params
# https://github.com/luizdepra/hugo-coder/wiki/Configurations#complete-example
[params]
    author = "Guillermo Estrada"
    info = "Full Stack Developer and Generative Artist (in progress...)"
    description = "Guillermo Estrada Dev Blog"
    keywords = "dev,blog,developer,go,golang,js,javascript,algorithms,generative art"
    avatarURL = "/images/avatar.jpg"
    footercontent = "Daydreamer, analytical brainiac, shameless romantic, factual magician, practical poet, irrational empath, generative artist, ninja coder and mind reader."
    repo = "phrozen/gestrada.dev"
    colorScheme = "auto"
    enableTwemoji = true

    customSCSS = ["scss/style.scss"]
    customJS = ["js/sketch.js"]

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[params.goatCounter]
    code = "gestrada"

[params.utterances]
    repo = "phrozen/gestrada.dev"     # https://utteranc.es/#heading-repository
    issueTerm = "pathname"            # https://utteranc.es/#heading-mapping
    label = "Label"                   # https://utteranc.es/#heading-issue-label
    theme = "preferred-color-scheme"  # https://utteranc.es/#heading-theme

[[params.social]]
    name = "Github"
    icon = "fa fa-github fa-2x"
    weight = 1
    url = "https://github.com/phrozen/"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin fa-2x"
    weight = 2
    url = "https://www.linkedin.com/in/phrozen/"
[[params.social]]
    name = "Twitter"
    icon = "fa fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/phrzn/"
[[params.social]]
    name = "Instagram"
    icon = "fa fa-instagram fa-2x"
    weight = 3
    url = "https://www.instagram.com/phrzn/"
[[params.social]]
    name = "RSS"
    icon = "fa fa-rss fa-2x"
    weight = 3
    url = "https://gestrada.dev/index.xml"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "about/"
